version: '3'

services:
    api:
        build: .
        env_file: compose.env
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            - mongo

    mongo:
        image: docker.io/bitnami/mongodb:4.4
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - 'mongodb_data:/bitnami/mongodb'
    
volumes:
    mongodb_data:
        driver: local